fix empty blocks
aurora-is-near/aurora-relayer pull request #128
Opened 2021-11-16 14:21 UTC by 0x3bfc

closes #127

2021-11-16 15:25 UTC, antonpaisov commented on src/indexer.ts
> +            //if (this.config.debug) console.debug(emptyBlock); // DEBUG
leftover comment,please remove

2021-11-16 15:25 UTC, antonpaisov commented on src/indexer.ts
> +            //if (this.config.debug) console.debug(query.toString()); // DEBUG
leftover comment

2021-11-16 15:26 UTC, antonpaisov commented on src/indexer.ts
>        //if (this.config.debug) console.debug(query.toString()); // DEBUG
same leftover

2021-11-16 17:16 UTC, antonpaisov approved these changes
lgtm, if well tested lets proceed.
we really need to unblock the graph by tomorrow morning the latest
cc @artob

2021-11-17 09:19 UTC, 0x3bfc commented on src/indexer.ts
> +            //if (this.config.debug) console.debug(emptyBlock); // DEBUG
This was left for future debugging.

2021-11-17 14:14 UTC, mfornet approved these changes
LGTM

2021-11-17 23:45 UTC, artob requested changes
The changes as they are would make indexing nondeterministic, so this needs work.

2021-11-17 23:45 UTC, artob commented on src/indexer.ts
> +    let timestamp = Math.floor(Date.now() / 1000); // init timestamp
This makes indexing nondeterministic: two parallel indexers will not produce the same database entries. That must be fixed. It's better for skip blocks to have no timestamps (it's a nullable column) than to have arbitrary timestamps.

2021-11-17 23:45 UTC, artob commented on src/indexer.ts
> +              timestamp + 1 // arbitrary timestamp = previous block.timestamp + 1
Better for skip blocks to have no timestamps (it's a nullable column) than to have arbitrary timestamps.

2021-11-17 23:45 UTC, artob commented on src/indexer.ts
> +              gas_used: 0, // FIXME: block.gasUsed,
There is no reason to retain `FIXME` comments here. Just use `emptyBlock.gasLimit` and `emptyBlock.gasUsed`.

2021-11-17 23:45 UTC, artob commented on src/indexer.ts
> +      timestamp = block.timestamp as number; // it is used only for empty blocks
This can be removed.

2021-11-17 23:45 UTC, artob commented on src/utils.ts
> +    timestamp: new Date(timestamp * 1000).toISOString(),
Better that skip blocks have no timestamp (it's a nullable column).

2021-11-18 12:18 UTC, artob approved these changes

2021-11-18 12:19 UTC, merged