Mix hash in eth get block by number
aurora-is-near/aurora-relayer pull request #131
Opened 2021-11-25 10:49 UTC by rahul10-pu

http post http://localhost:8545 jsonrpc=2.0 id=1 method=eth_getBlockByNumber `params:='["72693775"]'
`
{
    "id": "1",
    "jsonrpc": "2.0",
    "result": {
        "difficulty": "0x0",
        "extraData": "0x",
        "gasLimit": "0x0",
        "gasUsed": "0x0",
        "hash": "0x5b3a0dbcf46beaf77e359c806c9de07ec6c1ec338c2bfb1083ccaf891d1cf8e7",
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "miner": "0x0000000000000000000000000000000000000000",
        "mixHash": "0x31363337383237393832",
        "nonce": "0x0000000000000000",
        "number": "0x455380f",
        "parentHash": "0xadfc249aab410ba01277472147499ccfad8f4409abdd765c8ed9b380582e2fa2",
        "receiptsRoot": "0x43d9fe9c7f68a695c3cd2ef7d98063c3eab4e25819dc5c1b2bf55234d8e68922",
        "sha3Uncles": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "size": "0xc7",
        "stateRoot": "0x935361bc84fd30e5e6857ffe895bea2711352e6460ebf9c28d6cac937fdd3061",
        "timestamp": null,
        "totalDifficulty": "0x0",
        "transactions": [],
        "transactionsRoot": "0x1223349a40d2ee10bd1bebb5889ef8018c8bc13359ed94b387810af96c6e4268",
        "uncles": []
    }
}
`

2021-11-26 06:04 UTC, joshuajbouw commented
In the code it returns empty bytes, but why is the example return not empty bytes?

2021-12-01 09:44 UTC, artob requested changes
LGTM, but needs one correction and also needs instructions to reload the affected stored procedure added to [the changelog](https://github.com/aurora-is-near/aurora-relayer/blob/master/CHANGES.md). Watch out for a merge conflict with #132 which will also update the changelog.

2021-12-01 09:44 UTC, artob commented on etc/schema/types/block_result.sql
> +    "mixHash" bytea,         -- 32 bytes
The column type should be `hash` instead of `bytea`, similarly to e.g. `block_result` columns.

2021-12-02 13:02 UTC, artob approved these changes
LGTM :+1: And I've verified that all the other uses of `RETURNS block_result` defer to this one, so looks good to go.

2021-12-02 13:03 UTC, artob commented on etc/schema/types/block_result.sql
> +    "mixHash" bytea,         -- 32 bytes
@rahul10-pu Please make sure to press the 'Resolve' button on discussions when they've been sorted.

2021-12-02 13:03 UTC, merged