Validate that transaction.output is a valid address
aurora-is-near/aurora-relayer pull request #132
Opened 2021-11-30 10:51 UTC by spilin

When transaction.output is not a valid address do not use it as `contractAddress`.

2021-11-30 16:27 UTC, antonpaisov approved these changes

2021-12-01 09:33 UTC, artob requested changes
LGTM, but needs instructions to reload the affected stored procedure added to [the changelog](https://github.com/aurora-is-near/aurora-relayer/blob/master/CHANGES.md).

2021-12-01 15:12 UTC, artob approved these changes
LGTM

2021-12-01 15:12 UTC, merged

2021-12-01 17:44 UTC, Sanmyohtet9 reviewed
<p>®</p>